/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {SectionProps} from "../section/SectionProps";
import type {SeoProps} from "@kickstartds/design-system/seo";

/**
 * Collection of sections (with their contents) to render on the page
 */
export type Sections = SectionProps[];
/**
 * Toggle default floating header behaviour set in global settings
 */
export type ToggleFloating = boolean;
/**
 * Toggle default inverted header behaviour set in global settings
 */
export type ToggleInverted = boolean;
/**
 * Override for logo
 */
export type Logo = string;
/**
 * Toggle default inverted footer behaviour set in global settings
 */
export type ToggleInverted1 = boolean;
/**
 * Override for logo
 */
export type Logo1 = string;
/**
 * CSS custom property overrides to be included in the global styles — layers on top of the selected theme
 */
export type LocalCSSCustomPropertyOverrides = string;
/**
 * Whether to hide breadcrumbs on this page
 */
export type HidePageBreadcrumbs = boolean;
/**
 * Select a token theme for this page — overrides the global theme setting
 */
export type Theme = string;
/**
 * Hide the Book a Demo button on this page
 */
export type HideBookADemoButton = boolean;

/**
 * Abstracts a page concept into JSON schema
 */
export interface PageProps {
  section?: Sections;
  header?: Header;
  footer?: Footer;
  token?: LocalCSSCustomPropertyOverrides;
  hidePageBreadcrumbs?: HidePageBreadcrumbs;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
  theme?: Theme;
  hideBookDemoButton?: HideBookADemoButton;
}
/**
 * Header settings for the page
 */
export interface Header {
  floating?: ToggleFloating;
  inverted?: ToggleInverted;
  logo?: Logo;
}
/**
 * Footer settings for the page
 */
export interface Footer {
  inverted?: ToggleInverted1;
  logo?: Logo1;
}
