/**
 * Component-contract tools for the component-builder MCP server.
 *
 * Contracts are generated by the design system (`scripts/contracts/bin/generate.mjs`)
 * and published at `dist/contracts/`. This module locates them, serves them, and
 * formats task-shaped answers for an agent:
 *
 *   list_component_contracts    the catalog, with coverage
 *   get_component_brief         the Markdown front door (PRD §8.2)
 *   get_component_contract      the full JSON, or one section of it
 *   get_component_anatomy       parts + composition only
 *   get_prop_visual_impact      bindings + axes: "what happens if I set this"
 *   lint_component_contracts    every derived contract issue, grouped
 *
 * Everything degrades gracefully: when no contract directory is present, the
 * tools say so and name the env var that points at one, rather than throwing.
 */

import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

const text = (value: string): CallToolResult => ({
  content: [{ type: "text", text: value }],
});

// ---------------------------------------------------------------------------
// Contract shapes (the parts these tools read)
// ---------------------------------------------------------------------------

interface IndexArtifact {
  contractId: string;
  component: string;
  path: string;
  address: string;
  origin: string;
}

interface ContractIndex {
  $format: string;
  format: string;
  contractVersion: string;
  artifacts: IndexArtifact[];
}

interface ContractBinding {
  prop: string;
  mechanism: string;
  parts: string[];
  affects?: string[];
  tokens?: string[];
  detail?: string;
  proven?: boolean;
}

interface AxisValue {
  api: unknown;
  class?: string | null;
  tokenSegment?: string | null;
  issues?: string[];
  proven?: boolean;
  discriminated?: boolean;
}

interface ContractAxis {
  prop: string;
  default?: unknown;
  values: AxisValue[];
}

interface ContractCoverage {
  score?: number | null;
  axes?: Record<string, { total: number; proven: number; missing: unknown[] }>;
}

interface ContractIssue {
  code: string;
  detail?: string;
  segments?: string[];
}

interface ComponentContract {
  $format: string;
  contractId: string;
  component: string;
  description?: string;
  api?: { schema?: string; required?: string[]; props?: Record<string, unknown> };
  anatomy?: unknown;
  axes?: ContractAxis[];
  default?: unknown;
  variants?: unknown[];
  bindings?: ContractBinding[];
  composition?: unknown;
  coverage?: ContractCoverage | null;
  issues?: ContractIssue[];
  generated?: unknown;
}

/**
 * Parsed JSON is external input. Each document was validated against
 * `schema/contract.schema.json` by the generator before being published, so
 * this boundary asserts the named shape after checking only the members these
 * tools dispatch on — checking every member here would duplicate that schema.
 */
function parseContract(value: unknown): ComponentContract | null {
  if (typeof value !== "object" || value === null) return null;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.$format !== "string") return null;
  if (typeof candidate.contractId !== "string") return null;
  if (typeof candidate.component !== "string") return null;
  return value as ComponentContract;
}

function parseIndex(value: unknown): ContractIndex | null {
  if (typeof value !== "object" || value === null) return null;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.format !== "string") return null;
  if (typeof candidate.contractVersion !== "string") return null;
  if (!Array.isArray(candidate.artifacts)) return null;
  return value as ContractIndex;
}

function readJson(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as unknown;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Locating the contract set
// ---------------------------------------------------------------------------

/**
 * Contracts are served only when `DESIGN_SYSTEM_CONTRACTS_DIR` points at a
 * generated `contracts/` directory.
 *
 * Deliberately no filesystem-walk fallback: this server runs both in production
 * and as an eval arm, and a fallback that finds the monorepo's own
 * `packages/design-system/contracts` would silently hand the contract tools to
 * every arm — turning an A/B into an A/A. Deployment configs set the variable.
 */
function candidates(): string[] {
  return process.env.DESIGN_SYSTEM_CONTRACTS_DIR
    ? [resolve(process.env.DESIGN_SYSTEM_CONTRACTS_DIR)]
    : [];
}

let cachedDir: string | null | undefined;

export function contractsDir(): string | null {
  if (cachedDir !== undefined) return cachedDir;
  cachedDir =
    candidates().find((dir) => existsSync(join(dir, "index.json"))) ?? null;
  return cachedDir;
}

/** Reset the resolution cache. Exported for tests. */
export function resetContractsDirCache(): void {
  cachedDir = undefined;
}

export function loadIndex(): ContractIndex | null {
  const dir = contractsDir();
  return dir ? parseIndex(readJson(join(dir, "index.json"))) : null;
}

export function loadContract(contractId: string): ComponentContract | null {
  const dir = contractsDir();
  return dir ? parseContract(readJson(join(dir, `${contractId}.contract.json`))) : null;
}

export function loadBrief(contractId: string): string | null {
  const dir = contractsDir();
  if (!dir) return null;
  try {
    return readFileSync(join(dir, `${contractId}.brief.md`), "utf8");
  } catch {
    return null;
  }
}

/**
 * The narrative sidecar (PRD §5.12), or null when there is none. It is
 * model-generated and advisory: it arrives attached to the contract it glosses,
 * never as its own tool, and never in the precision queries.
 */
export function loadNarrative(contractId: string): unknown {
  const dir = contractsDir();
  if (!dir) return null;
  return readJson(join(dir, `${contractId}.narrative.json`));
}

/** Resolve a user-supplied name (contractId, folder id, or display name). */
export function resolveContractId(name: string): string | null {
  const index = loadIndex();
  if (!index) return null;
  const wanted = name.trim().toLowerCase();
  const match = (predicate: (artifact: IndexArtifact) => boolean) =>
    index.artifacts.find(predicate)?.contractId ?? null;

  return (
    match((artifact) => artifact.contractId.toLowerCase() === wanted) ??
    match((artifact) => artifact.component.toLowerCase() === wanted) ??
    match((artifact) => artifact.contractId === wanted.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""))
  );
}

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

function unavailable(): CallToolResult {
  return text(
    [
      "Component contracts are not available in this environment.",
      "",
      "They are generated by the design system:",
      "  node scripts/contracts/bin/generate.mjs --emit-stories",
      "  pnpm --filter @kickstartds/design-system build-storybook",
      "  node scripts/contracts/bin/generate.mjs",
      "",
      "Point DESIGN_SYSTEM_CONTRACTS_DIR at a generated `contracts/` directory",
      "to serve a specific set.",
    ].join("\n"),
  );
}

function unknownContract(name: string): CallToolResult {
  const ids = loadIndex()?.artifacts.map((artifact) => artifact.contractId) ?? [];
  return text(
    [
      `No contract for ${JSON.stringify(name)}.`,
      "",
      `Available (${ids.length}): ${ids.join(", ")}`,
      "",
      "Use `list_component_contracts` for coverage details. A display name",
      '("Blog Aside") resolves as well as a contractId ("blog-aside").',
    ].join("\n"),
  );
}

// ---------------------------------------------------------------------------
// Tool handlers
// ---------------------------------------------------------------------------

interface NameArgs {
  name: string;
}

interface ContractArgs extends NameArgs {
  section?: string;
}

interface PropImpactArgs extends NameArgs {
  prop?: string;
}

const CONTRACT_SECTIONS: Record<string, true> = {
  api: true,
  anatomy: true,
  axes: true,
  default: true,
  variants: true,
  bindings: true,
  composition: true,
  coverage: true,
  issues: true,
  generated: true,
};

export function handleListComponentContracts(args: {
  includeCoverage?: boolean;
}): CallToolResult {
  const index = loadIndex();
  if (!index) return unavailable();

  const includeCoverage = args.includeCoverage !== false;
  const lines = [
    `Component contracts — ${index.format} (set ${index.contractVersion}), ${index.artifacts.length} components`,
    "",
  ];

  for (const artifact of index.artifacts) {
    const contract = loadContract(artifact.contractId);
    const bits = [artifact.contractId, "—", artifact.component];
    if (includeCoverage && contract) {
      bits.push(`coverage ${contract.coverage?.score ?? "n/a"}`);
      bits.push(`${contract.variants?.length ?? 0} variants`);
      if (contract.issues?.length) bits.push(`⚠ ${contract.issues.length} issues`);
    }
    lines.push(`  ${bits.join(" ")}`);
  }

  lines.push(
    "",
    "Prototypical tool calls:",
    "  get_component_brief            — orientation, the token-cheap default",
    "  get_prop_visual_impact         — what setting a prop actually changes",
    "  get_component_contract         — the full derived contract",
  );
  return text(lines.join("\n"));
}

export function handleGetComponentBrief(args: NameArgs): CallToolResult {
  if (!contractsDir()) return unavailable();
  const contractId = resolveContractId(args.name);
  if (!contractId) return unknownContract(args.name);

  const brief = loadBrief(contractId);
  if (brief) return text(brief);
  return text(
    `No brief for ${contractId} (the contract exists, but the brief was not generated).`,
  );
}

export function handleGetComponentContract(args: ContractArgs): CallToolResult {
  if (!contractsDir()) return unavailable();
  const contractId = resolveContractId(args.name);
  if (!contractId) return unknownContract(args.name);
  const contract = loadContract(contractId);
  if (!contract) return unknownContract(args.name);

  if (args.section) {
    const section = args.section.toLowerCase();
    if (!Object.hasOwn(CONTRACT_SECTIONS, section)) {
      return text(
        `Unknown section ${JSON.stringify(args.section)}. Available: ${Object.keys(
          CONTRACT_SECTIONS,
        ).join(", ")}`,
      );
    }
    const key = section as keyof ComponentContract;
    return text(
      JSON.stringify(
        { contractId, component: contract.component, [section]: contract[key] },
        null,
        2,
      ),
    );
  }

  const narrative = loadNarrative(contractId);
  if (narrative) {
    return text(
      JSON.stringify({ ...contract, narrative }, null, 2),
    );
  }
  return text(JSON.stringify(contract, null, 2));
}

export function handleGetComponentAnatomy(args: NameArgs): CallToolResult {
  if (!contractsDir()) return unavailable();
  const contractId = resolveContractId(args.name);
  if (!contractId) return unknownContract(args.name);
  const contract = loadContract(contractId);
  if (!contract) return unknownContract(args.name);

  return text(
    JSON.stringify(
      {
        contractId,
        component: contract.component,
        anatomy: contract.anatomy,
        composition: contract.composition,
      },
      null,
      2,
    ),
  );
}

export function handleGetPropVisualImpact(args: PropImpactArgs): CallToolResult {
  if (!contractsDir()) return unavailable();
  const contractId = resolveContractId(args.name);
  if (!contractId) return unknownContract(args.name);
  const contract = loadContract(contractId);
  if (!contract) return unknownContract(args.name);

  const bindings = contract.bindings ?? [];
  const axes = contract.axes ?? [];
  const wanted = args.prop?.trim();

  const selectedBindings = wanted
    ? bindings.filter((binding) => binding.prop === wanted)
    : bindings;
  const selectedAxes = wanted ? axes.filter((axis) => axis.prop === wanted) : axes;

  if (wanted && selectedBindings.length === 0 && selectedAxes.length === 0) {
    return text(
      [
        `No binding or axis for ${JSON.stringify(wanted)} on ${contractId}.`,
        "",
        `Props with a visual impact: ${[
          ...new Set(bindings.map((binding) => binding.prop)),
        ].join(", ")}`,
      ].join("\n"),
    );
  }

  // A binding's templated token names are generated from the axes join, so the
  // agent can construct any token name without a lookup (PRD §5.8).
  const templatedTokens = selectedBindings.flatMap((binding) => binding.tokens ?? []);

  return text(
    JSON.stringify(
      {
        contractId,
        component: contract.component,
        prop: wanted ?? null,
        bindings: selectedBindings,
        axes: selectedAxes,
        templatedTokens,
        note:
          "mechanism is how the prop becomes visible; templatedTokens use the axes values, e.g. --dsa-button_{variant}--background-color.",
      },
      null,
      2,
    ),
  );
}

export function handleLintComponentContracts(): CallToolResult {
  const index = loadIndex();
  if (!index) return unavailable();

  const issues: ContractIssue[] = [];
  for (const artifact of index.artifacts) {
    for (const issue of loadContract(artifact.contractId)?.issues ?? []) {
      issues.push(issue);
    }
  }

  if (issues.length === 0) {
    return text(`No contract issues across ${index.artifacts.length} components.`);
  }

  const lines = [
    `${issues.length} contract issue(s) across ${index.artifacts.length} components`,
    "",
    JSON.stringify(issues, null, 2),
  ];
  return text(lines.join("\n"));
}

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

const FORMAT_GUIDE = `# Component contracts

A contract is one JSON file per component, fully derived from the component's
JSON Schema, its rendered Storybook stories, and the design-token catalogs. It
exists to answer a question no other artifact answers: **what happens visually
when I set a prop, and which token do I change to restyle it.**

Four ideas are not self-evident from the field names:

1. **axes is a join across three vocabularies.** Each variant value appears three
   times: \`api\` (what you write), \`class\` (what appears in the DOM), and
   \`tokenSegment\` (the \`_<variant>\` segment of the component tokens that theme
   it). \`null\` means the value produces no class or has no matching token.
   \`issues\` reports a value that fails to join — that is a real defect, not noise.

2. **variants are deltas, not full states.** Each entry lists only what changed
   relative to the declared default, and is backed by a story and a screenshot.
   Absence from \`variants\` means "no story proves it", not "it does not exist" —
   \`coverage\` says which values are proven.

3. **bindings say how a prop becomes visible.** \`mechanism\` is one of
   \`content | presence | class-toggle | token-swap | attribute | element-swap |
   layout | none\`. \`presence\` changes the DOM (spacing may shift);
   \`token-swap\` is themeable and the templated token names tell you which tokens
   to reach for; \`none\` means do not waste attention there.

4. **coverage bounds what the contract asserts.** \`coverage.axes[prop].missing\`
   lists enum values with no story. Anything missing is unproven, not impossible.

The default baseline is declared (\`{Name}Defaults.ts\`), not inferred, so every
authored story is a variant. \`default.parts[].styles\` carries three values per
property: \`token\` (what to change), \`resolves\` (the semantic token it bottoms
out in; \`null\` means a literal, an off-system value), and \`computed\` (the
rendered value).

Read \`get_component_brief\` first; fetch the full contract only when you need the
evidence.`;

export function readContractResource(
  uri: string,
): { uri: string; mimeType: string; text: string } | null {
  if (uri === "contracts://format-guide") {
    return { uri, mimeType: "text/markdown", text: FORMAT_GUIDE };
  }
  if (uri === "contracts://index") {
    const index = loadIndex();
    return {
      uri,
      mimeType: "application/json",
      text: JSON.stringify(
        index ?? { error: "no contract set found" },
        null,
        2,
      ),
    };
  }
  if (uri.startsWith("contracts://")) {
    const contract = loadContract(uri.replace("contracts://", ""));
    if (contract) {
      return { uri, mimeType: "application/json", text: JSON.stringify(contract, null, 2) };
    }
  }
  return null;
}
