/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The plans that are compared, one per column
 *
 * @minItems 2
 * @maxItems 5
 */
export type Plans = [Plan, Plan] | [Plan, Plan, Plan] | [Plan, Plan, Plan, Plan] | [Plan, Plan, Plan, Plan, Plan];
/**
 * Name of the plan, e.g. "Basic"
 */
export type Name = string;
/**
 * Price of the plan, e.g. "$99" or "On request"
 */
export type Price = string;
/**
 * The period the price refers to, e.g. "Per month". Leave empty for a one-off price
 */
export type PricePeriod = string;
/**
 * Optional badge above the plan name, e.g. "Popular". Leave empty for no badge
 */
export type Badge = string;
/**
 * Present this plan as the recommended one, on an inverted column
 */
export type Highlight = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * The URL to link to when the button is clicked
 */
export type URL = string;
/**
 * Variant of the button. Defaults to `primary` on a highlighted plan and `tertiary` on a regular one
 */
export type Variant = "primary" | "secondary" | "tertiary";
/**
 * The features that are compared, one per row
 *
 * @minItems 1
 * @maxItems 12
 */
export type FeatureRows =
  | [FeatureRow]
  | [FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow, FeatureRow]
  | [
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow
    ]
  | [
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow
    ]
  | [
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow,
      FeatureRow
    ];
/**
 * Name of the feature this row compares
 */
export type Label1 = string;
/**
 * One entry per plan, in the same order as `plans`. A `text` for a comparable value, an `icon` for included or not included, neither for an empty cell
 *
 * @minItems 2
 * @maxItems 5
 */
export type Values =
  | [Value, Value]
  | [Value, Value, Value]
  | [Value, Value, Value, Value]
  | [Value, Value, Value, Value, Value];
/**
 * The value itself, e.g. "Unlimited" or "01"
 */
export type Text = string;
/**
 * An icon instead of text, e.g. "check" for included or "close" for not included
 */
export type Icon = string;

/**
 * Component used to compare what several plans include, feature by feature
 */
export interface ComparisonTableProps {
  plans?: Plans;
  featureRow?: FeatureRows;
}
export interface Plan {
  name?: Name;
  price?: Price;
  pricePeriod?: PricePeriod;
  badge?: Badge;
  highlight?: Highlight;
  cta?: CallToAction;
}
/**
 * The button that starts this plan
 */
export interface CallToAction {
  label?: Label;
  url?: URL;
  variant?: Variant;
}
export interface FeatureRow {
  label?: Label1;
  value?: Values;
}
export interface Value {
  text?: Text;
  icon?: Icon;
}
