/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Form component for submitting utility meter readings for electricity and water
 */
export interface MeterReadingFormProps {
  /**
   * Main heading of the form
   */
  title?: string;
  billingTypeLabel?: string;
  customerNumberLabel?: string;
  salutationLabel?: string;
  firstNameLabel?: string;
  lastNameLabel?: string;
  streetLabel?: string;
  cityLabel?: string;
  emailLabel?: string;
  phoneLabel?: string;
  electricityHeading?: string;
  electricityMeterNumberLabel?: string;
  electricityMeterTypeLabel?: string;
  electricityReadingLabel?: string;
  electricityFeedInLabel?: string;
  electricitySecondMeterLabel?: string;
  electricityThirdMeterLabel?: string;
  electricityFourthMeterLabel?: string;
  waterHeading?: string;
  waterMeterNumberLabel?: string;
  waterReadingLabel?: string;
  uploadLabel?: string;
  uploadButtonLabel?: string;
  consentLabel?: string;
  submitButtonLabel?: string;
}
