/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the plans share the available width equally, or fill the row at their own minimum width
 */
export type Layout = "equal" | "auto";
/**
 * The plans to present, in the order they should be read
 *
 * @minItems 1
 * @maxItems 4
 */
export type Plans = [Plan] | [Plan, Plan] | [Plan, Plan, Plan] | [Plan, Plan, Plan, Plan];
/**
 * Name of the plan, e.g. "Basic"
 */
export type Name = string;
/**
 * Price of the plan, e.g. "$99" or "On request"
 */
export type Price = string;
/**
 * The period the price refers to, e.g. "per month". Leave empty for a one-off price
 */
export type PricePeriod = string;
/**
 * Short description of what the plan is for and who it suits
 */
export type Description = string;
/**
 * Optional badge above the plan name, e.g. "Popular". Leave empty for no badge
 */
export type Badge = string;
/**
 * Present this plan as the recommended one, on an inverted surface
 */
export type Highlight = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * The URL to link to when the button is clicked
 */
export type URL = string;
/**
 * Variant of the button. Defaults to `primary` on a highlighted plan and `tertiary` on a regular one
 */
export type Variant = "primary" | "secondary" | "tertiary";
/**
 * Heading above the list of what the plan includes
 */
export type FeatureListTitle = string;
/**
 * What the plan includes, one entry per line
 *
 * @minItems 1
 * @maxItems 10
 */
export type IncludedFeatures =
  | [IncludedFeature]
  | [IncludedFeature, IncludedFeature]
  | [IncludedFeature, IncludedFeature, IncludedFeature]
  | [IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature]
  | [IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature]
  | [IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature, IncludedFeature]
  | [
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature
    ]
  | [
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature
    ]
  | [
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature
    ]
  | [
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature,
      IncludedFeature
    ];
/**
 * The description of the feature
 */
export type Text = string;
/**
 * Optional icon in front of the entry, e.g. "check". Leave empty for a plain list
 */
export type Icon = string;

/**
 * Component used to present several pricing plans side by side, one of them optionally recommended
 */
export interface PricingPlansProps {
  layout?: Layout;
  plan?: Plans;
}
export interface Plan {
  name?: Name;
  price?: Price;
  pricePeriod?: PricePeriod;
  description?: Description;
  badge?: Badge;
  highlight?: Highlight;
  cta?: CallToAction;
  featureListTitle?: FeatureListTitle;
  featureList?: IncludedFeatures;
}
/**
 * The button that starts this plan
 */
export interface CallToAction {
  label?: Label;
  url?: URL;
  variant?: Variant;
}
export interface IncludedFeature {
  text?: Text;
  icon?: Icon;
}
