/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {HeaderProps} from "@kickstartds/design-system/header";
import type {FooterProps} from "@kickstartds/design-system/footer";
import type {SeoProps} from "@kickstartds/design-system/seo";

/**
 * Content of the icon sprite for this project
 */
export type IconSprite = string;
/**
 * CSS custom property overrides to be included in the global styles — layers on top of the selected theme
 */
export type CSSCustomPropertyOverrides = string;
/**
 * Whether to hide breadcrumbs across the site
 */
export type HideBreadcrumbs = boolean;
/**
 * Select a token theme to apply globally — overrides default branding tokens
 */
export type Theme = string;
/**
 * Show a fixed 'Book a Demo' button on all pages
 */
export type Enabled = boolean;
/**
 * Label text for the Book a Demo button
 */
export type Label = string;
/**
 * URL the Book a Demo button links to
 */
export type URL = string;
/**
 * Visual variant of the Book a Demo button
 */
export type Variant = "primary" | "secondary" | "tertiary";

/**
 * Abstracts global settings made for a website into JSON Schema
 */
export interface SettingsProps {
  /**
   * Referenced component HeaderProps
   */
  header: HeaderProps;
  /**
   * Referenced component FooterProps
   */
  footer: FooterProps;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
  iconSprite?: IconSprite;
  token?: CSSCustomPropertyOverrides;
  hideBreadcrumbs?: HideBreadcrumbs;
  theme?: Theme;
  bookDemoButton?: BookADemoButton;
}
/**
 * Configure the fixed Book a Demo button shown on all pages
 */
export interface BookADemoButton {
  enabled?: Enabled;
  label?: Label;
  url?: URL;
  variant?: Variant;
}
