/**
 * Generate a Storybook story per component that renders the declared default
 * baseline (PRD §5.6.2).
 *
 * No authored story describes the default — none of them was written to be it —
 * so one has to exist before there is anything to diff variants against. It is
 * generated from schema + defaults, so principle 8 ("derived over authored")
 * still holds, and it rides the existing decorators, providers and token layer
 * unchanged, which is the whole reason for doing it inside Storybook rather
 * than rendering the component ourselves.
 */

import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

export const DEFAULT_EXPORT = "ContractDefault";
export const DEFAULT_TITLE_GROUP = "Contract Defaults";

const pascal = (id) =>
  id
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

/**
 * Storybook's own id derivation, for the ids we hand to Playwright. Note that
 * `sanitize` does NOT split camelCase — `BlogAside` becomes `blogaside`, not
 * `blog-aside` — whereas the story name IS split out of the export name first.
 */
const sanitize = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const nameFromExport = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1 $2");

export const defaultStoryId = (id) =>
  `${sanitize(`${DEFAULT_TITLE_GROUP}/${pascal(id)}`)}--${sanitize(nameFromExport(DEFAULT_EXPORT))}`;

/**
 * Deliberately minimal CSF: no `getArgsShared`, no `pack`, no parameters. The
 * args we pass ARE the declared configuration, and anything else layered on top
 * would quietly change the baseline we are trying to observe.
 */
function storyFile(id, config) {
  const Name = pascal(id);
  return `/* GENERATED by scripts/contract-spike — do not edit, do not commit. */
import type { Meta, StoryObj } from "@storybook/react-vite";

import { ${Name} } from "../components/${id}/${Name}Component";

const meta: Meta<typeof ${Name}> = {
  title: "${DEFAULT_TITLE_GROUP}/${Name}",
  component: ${Name},
};

export default meta;

export const ${DEFAULT_EXPORT}: StoryObj<typeof ${Name}> = {
  args: ${JSON.stringify(config, null, 2)} as never,
};
`;
}

/**
 * @param {string} root design-system package root
 * @param {Array<{id: string, config: object}>} entries
 * @returns {string} the directory written
 */
export function writeDefaultStories(root, entries) {
  const dir = join(root, "src/contract-defaults");
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  for (const { id, config } of entries)
    writeFileSync(join(dir, `${id}.stories.tsx`), storyFile(id, config));
  return dir;
}
