import Autocomplete from "@mui/material/Autocomplete";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import FormControlLabel from "@mui/material/FormControlLabel";
import ListSubheader from "@mui/material/ListSubheader";
import Switch from "@mui/material/Switch";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import semanticCatalog from "@kickstartds/design-system/tokens/semantic-token-catalog.json";
import globalCss from "@kickstartds/design-system/global.css?raw";
import { FC, Fragment, useEffect, useMemo, useState } from "react";

interface SemanticToken {
  name: string;
  value: string;
  valueType: string;
  category: string;
}

/**
 * Resolve all token var() references to their computed CSS values.
 *
 * Injects the semantic token CSS (tokens.css) + the current branding CSS
 * (from localStorage, written by TokenContext) into hidden `<style>` tags
 * so the browser's CSS engine can resolve the full chain:
 *   semantic → branding → literal value
 *
 * Then reads back computed values via getComputedStyle on :root.
 */
function useResolvedValues(tokens: SemanticToken[]): Map<string, string> {
  const [resolved, setResolved] = useState<Map<string, string>>(new Map());

  useEffect(() => {
    // Read the current branding CSS generated by TokenContext
    const brandingCss = localStorage.getItem("css") || "";

    // Inject both layers so the browser can resolve the full chain.
    // Use global.css (which has live calc()-based semantic token definitions)
    // instead of the pre-compiled tokens.css (which has baked-in default values
    // and won't respond to branding token overrides).
    const semanticStyle = document.createElement("style");
    semanticStyle.setAttribute("data-token-resolver", "semantic");
    semanticStyle.textContent = globalCss;

    const brandingStyle = document.createElement("style");
    brandingStyle.setAttribute("data-token-resolver", "branding");
    brandingStyle.textContent = brandingCss;

    document.head.appendChild(semanticStyle);
    document.head.appendChild(brandingStyle);

    // Force a style recalc, then read computed values
    const root = document.documentElement;
    const cs = getComputedStyle(root);

    // Two probe elements: one normal, one inside an inverted context
    const probe = document.createElement("div");
    probe.style.position = "absolute";
    probe.style.visibility = "hidden";
    document.body.appendChild(probe);

    const invertedWrapper = document.createElement("div");
    invertedWrapper.setAttribute("ks-inverted", "");
    invertedWrapper.style.position = "absolute";
    invertedWrapper.style.visibility = "hidden";
    const invertedProbe = document.createElement("div");
    invertedWrapper.appendChild(invertedProbe);
    document.body.appendChild(invertedWrapper);

    const map = new Map<string, string>();
    for (const token of tokens) {
      if (!token.value.includes("var(")) {
        map.set(token.name, token.value);
        continue;
      }

      const isColor = COLOR_CATEGORIES.includes(token.category);
      const isInverted = token.name.includes("-inverted");
      const activeProbe = isInverted ? invertedProbe : probe;

      if (isColor) {
        // Colors need full computation via a real CSS property
        activeProbe.style.color = `var(${token.name})`;
        const computed = getComputedStyle(activeProbe).color;
        activeProbe.style.color = "";
        if (computed && computed !== "rgb(0, 0, 0)") {
          map.set(token.name, computed);
        }
      } else {
        // Non-color tokens: read the resolved custom property from :root
        const raw = cs.getPropertyValue(token.name).trim();
        if (raw && !raw.includes("var(")) {
          map.set(token.name, raw);
        }
      }
    }

    probe.remove();
    invertedWrapper.remove();
    setResolved(map);

    // Clean up injected styles
    semanticStyle.remove();
    brandingStyle.remove();
  }, [tokens]);

  return resolved;
}

/** Flatten the categorized catalog into a flat sorted list. */
function buildTokenList(): SemanticToken[] {
  const list: SemanticToken[] = [];
  for (const [category, tokens] of Object.entries(semanticCatalog)) {
    for (const [name, meta] of Object.entries(
      tokens as Record<string, { value: string; valueType: string }>,
    )) {
      list.push({
        name,
        value: meta.value,
        valueType: meta.valueType,
        category,
      });
    }
  }
  return list;
}

const allTokens = buildTokenList();

// ── Category inference from token metadata ──────────────────────────

/** Reverse lookup: semantic token name → category. */
const tokenToCategory: Record<string, string> = {};
for (const [cat, tokens] of Object.entries(semanticCatalog)) {
  for (const name of Object.keys(tokens as Record<string, unknown>)) {
    tokenToCategory[name] = cat;
  }
}

const COLOR_CATEGORIES = [
  "Background Color",
  "Border Color",
  "Color",
  "Text Color",
];
const DIMENSION_CATEGORIES = ["Spacing", "Border Radius", "Border Width"];
const TIMING_CATEGORIES = ["Transition", "Duration"];

function getRelatedCategories(category: string): string[] {
  if (COLOR_CATEGORIES.includes(category)) return COLOR_CATEGORIES;
  if (DIMENSION_CATEGORIES.includes(category)) return DIMENSION_CATEGORIES;
  if (TIMING_CATEGORIES.includes(category)) return TIMING_CATEGORIES;
  return [category];
}

function inferFromTokenName(tokenName: string): string[] {
  const suffix = tokenName.split("--").pop() || "";
  if (/color|fill|stroke/.test(suffix)) return COLOR_CATEGORIES;
  if (/^font$/.test(suffix)) return ["Font"];
  if (/font-size/.test(suffix)) return ["Font Size"];
  if (/font-weight/.test(suffix)) return ["Font Weight"];
  if (/font-family/.test(suffix)) return ["Font Family"];
  if (
    /gap|padding|margin|spacing|width|height|flex-basis|max-width|min-width/.test(
      suffix,
    )
  )
    return DIMENSION_CATEGORIES;
  if (/border-radius|radius/.test(suffix)) return ["Border Radius"];
  if (/border-width/.test(suffix)) return ["Border Width"];
  if (/shadow|box-shadow/.test(suffix)) return ["Shadow"];
  if (/transition|transform/.test(suffix)) return TIMING_CATEGORIES;
  return [];
}

/**
 * Given a component token name and its referenced token, infer which
 * semantic catalog categories are relevant for the reference picker.
 */
export function inferTokenCategories(
  tokenName: string,
  referencedToken: string | null,
): string[] {
  if (referencedToken) {
    const cat = tokenToCategory[referencedToken];
    if (cat) return getRelatedCategories(cat);
  }
  return inferFromTokenName(tokenName);
}

/** Shared box dimensions for all preview swatches. */
const SWATCH = { width: 20, height: 20, flexShrink: 0 } as const;

/** Renders an inline visual preview appropriate for the token type. */
function TokenPreview({
  category,
  resolvedValue,
}: {
  category: string;
  resolvedValue: string | undefined;
}) {
  if (!resolvedValue) return null;
  const value = resolvedValue;

  // ── Colors ──
  if (COLOR_CATEGORIES.includes(category)) {
    return (
      <Box
        sx={{
          ...SWATCH,
          borderRadius: "3px",
          border: "1px solid",
          borderColor: "divider",
          backgroundColor: value,
        }}
      />
    );
  }

  // ── Border Radius ──
  if (category === "Border Radius") {
    return (
      <Box
        sx={{
          ...SWATCH,
          borderRadius: value,
          border: "2px solid",
          borderColor: "text.secondary",
          bgcolor: "transparent",
        }}
      />
    );
  }

  // ── Border Width ──
  if (category === "Border Width") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Box
          sx={{
            width: "100%",
            height: value,
            minHeight: 1,
            maxHeight: SWATCH.height,
            bgcolor: "text.secondary",
            borderRadius: "1px",
          }}
        />
      </Box>
    );
  }

  // ── Spacing / Dimension ──
  if (category === "Spacing") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
        }}
      >
        <Box
          sx={{
            height: 6,
            width: value,
            minWidth: 2,
            maxWidth: SWATCH.width,
            bgcolor: "primary.main",
            borderRadius: "1px",
          }}
        />
      </Box>
    );
  }

  // ── Shadow ──
  if (category === "Shadow") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Box
          sx={{
            width: 14,
            height: 14,
            borderRadius: "2px",
            bgcolor: "background.paper",
            boxShadow: value,
          }}
        />
      </Box>
    );
  }

  // ── Font Size ──
  if (category === "Font Size") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        <Typography
          sx={{
            fontSize: value,
            lineHeight: 1,
            fontWeight: 600,
            // Cap visual size to keep it within the swatch
            transform: `scale(${Math.min(1, 18 / (parseFloat(value) || 16))})`,
            transformOrigin: "center",
          }}
        >
          A
        </Typography>
      </Box>
    );
  }

  // ── Font Weight ──
  if (category === "Font Weight") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Typography sx={{ fontSize: 12, fontWeight: value, lineHeight: 1 }}>
          A
        </Typography>
      </Box>
    );
  }

  // ── Font Family ──
  if (category === "Font Family") {
    return (
      <Box
        sx={{
          ...SWATCH,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Typography sx={{ fontSize: 12, fontFamily: value, lineHeight: 1 }}>
          Aa
        </Typography>
      </Box>
    );
  }

  // ── Transition / Duration ──
  if (TIMING_CATEGORIES.includes(category)) {
    // Simple pill whose width hints at relative duration
    const ms = parseFloat(value) * (value.includes("ms") ? 1 : 1000);
    const barWidth = Math.max(4, Math.min(SWATCH.width, ms / 25));
    return (
      <Box sx={{ ...SWATCH, display: "flex", alignItems: "center" }}>
        <Box
          sx={{
            height: 6,
            width: barWidth,
            bgcolor: "warning.main",
            borderRadius: "3px",
          }}
        />
      </Box>
    );
  }

  // Fallback: no preview for unknown categories
  return null;
}

interface TokenReferencePickerProps {
  /** Current raw value like "var(--ks-spacing-l)" or "" */
  value: string;
  /** Called with the selected var() value */
  onChange: (value: string) => void;
  /** Called when the picker is dismissed */
  onClose: () => void;
  /** Suggested semantic categories inferred from token metadata. */
  suggestedCategories?: string[];
}

export const TokenReferencePicker: FC<TokenReferencePickerProps> = ({
  value,
  onChange,
  onClose,
  suggestedCategories,
}) => {
  const hasSuggestions =
    suggestedCategories !== undefined && suggestedCategories.length > 0;
  const [showAll, setShowAll] = useState(!hasSuggestions);
  const [includeInverted, setIncludeInverted] = useState(false);

  // Filter token list by category + inverted toggle
  const filteredTokens = useMemo(() => {
    let list = allTokens;
    if (!showAll && hasSuggestions) {
      list = list.filter((t) => suggestedCategories!.includes(t.category));
    }
    if (!includeInverted) {
      list = list.filter((t) => !t.name.includes("-inverted"));
    }
    return list;
  }, [showAll, hasSuggestions, suggestedCategories, includeInverted]);

  // Resolve var() chains to computed values for previews
  const resolvedValues = useResolvedValues(filteredTokens);

  // Parse current value to find the selected token
  const selectedToken = useMemo(() => {
    const match = value.match(/^var\((--ks-[^)]+)\)$/);
    if (!match) return null;
    return allTokens.find((t) => t.name === match[1]) ?? null;
  }, [value]);

  return (
    <Box>
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: 0.5,
        }}
      >
        {hasSuggestions && (
          <Button
            size="small"
            onMouseDown={(e) => e.preventDefault()}
            onClick={() => setShowAll((p) => !p)}
            sx={{ fontSize: "0.7rem", textTransform: "none", py: 0 }}
          >
            {showAll
              ? `Show matching (${suggestedCategories!.join(", ")})`
              : "Show all categories"}
          </Button>
        )}
        <FormControlLabel
          onMouseDown={(e) => e.preventDefault()}
          control={
            <Switch
              size="small"
              checked={includeInverted}
              onChange={(_, checked) => setIncludeInverted(checked)}
            />
          }
          label="Inverted"
          slotProps={{
            typography: { fontSize: "0.7rem" },
          }}
          sx={{ ml: "auto", mr: 0 }}
        />
      </Box>
      <Autocomplete<SemanticToken, false, false, false>
        open
        size="small"
        options={filteredTokens}
        value={selectedToken}
        groupBy={(option) => option.category}
        getOptionLabel={(option) => option.name}
        isOptionEqualToValue={(opt, val) => opt.name === val.name}
        filterOptions={(options, { inputValue }) => {
          if (!inputValue) return options;
          const lower = inputValue.toLowerCase();
          return options.filter(
            (o) =>
              o.name.toLowerCase().includes(lower) ||
              o.category.toLowerCase().includes(lower),
          );
        }}
        onChange={(_, token) => {
          if (token) {
            onChange(`var(${token.name})`);
          }
          onClose();
        }}
        onClose={(_event, reason) => {
          if (reason === "escape") onClose();
        }}
        renderInput={(params) => (
          <TextField
            {...params}
            placeholder="Search tokens…"
            autoFocus
            size="small"
          />
        )}
        renderOption={({ key, ...props }, option) => {
          const resolved = resolvedValues.get(option.name);
          return (
            <Box
              component="li"
              key={key}
              {...props}
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.75,
                fontSize: "0.75rem",
                py: 0.25,
              }}
            >
              <TokenPreview
                category={option.category}
                resolvedValue={resolved}
              />
              <Typography
                variant="body2"
                sx={{
                  fontFamily: "monospace",
                  fontSize: "0.72rem",
                  flex: 1,
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                }}
              >
                {option.name}
              </Typography>
              <Typography
                variant="caption"
                sx={{
                  color: "text.secondary",
                  fontFamily: "monospace",
                  fontSize: "0.65rem",
                  flexShrink: 0,
                  whiteSpace: "nowrap",
                }}
              >
                {resolved || option.value}
              </Typography>
            </Box>
          );
        }}
        renderGroup={(params) => (
          <Fragment key={params.key}>
            <ListSubheader
              sx={{
                fontWeight: 700,
                fontSize: "0.7rem",
                textTransform: "uppercase",
                lineHeight: "28px",
                letterSpacing: "0.05em",
              }}
            >
              {params.group}
            </ListSubheader>
            {params.children}
          </Fragment>
        )}
        slotProps={{
          popper: { sx: { zIndex: 1500, minWidth: 340 } },
          listbox: { sx: { maxHeight: 300 } },
        }}
        sx={{ width: "100%" }}
      />
    </Box>
  );
};
