/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogTeaserProps} from "../blog-teaser/BlogTeaserProps";
import type {BusinessCardProps} from "../business-card/BusinessCardProps";
import type {ButtonProps} from "../button/ButtonProps";
import type {ContactProps} from "../contact/ContactProps";
import type {ContentNavProps} from "../content-nav/ContentNavProps";
import type {CtaProps} from "../cta/CtaProps";
import type {DividerProps} from "../divider/DividerProps";
import type {DownloadsProps} from "../downloads/DownloadsProps";
import type {EventLatestTeaserProps} from "../event-latest-teaser/EventLatestTeaserProps";
import type {EventListTeaserProps} from "../event-list-teaser/EventListTeaserProps";
import type {FaqProps} from "../faq/FaqProps";
import type {FeaturesProps} from "../features/FeaturesProps";
import type {GalleryProps} from "../gallery/GalleryProps";
import type {HeadlineProps} from "../headline/HeadlineProps";
import type {HeroProps} from "../hero/HeroProps";
import type {HtmlProps} from "../html/HtmlProps";
import type {ImageStoryProps} from "../image-story/ImageStoryProps";
import type {ImageTextProps} from "../image-text/ImageTextProps";
import type {LogosProps} from "../logos/LogosProps";
import type {MosaicProps} from "../mosaic/MosaicProps";
import type {SliderProps} from "../slider/SliderProps";
import type {StatsProps} from "../stats/StatsProps";
import type {TeaserCardProps} from "../teaser-card/TeaserCardProps";
import type {TestimonialsProps} from "../testimonials/TestimonialsProps";
import type {TextProps} from "../text/TextProps";
import type {VideoCurtainProps} from "../video-curtain/VideoCurtainProps";

/**
 * Sets the minimum width for each half of the split layout
 */
export type ContentMinimumWidth = "narrow" | "medium" | "wide";
/**
 * Sets the space between the content inside the two halves of the split layout
 */
export type ContentGutter = "small" | "default" | "large" | "none";
/**
 * Reverses the order of the sections on mobile devices
 */
export type MobileReverse = boolean;
/**
 * Aligns the content vertically within the sections
 */
export type VerticalAlignment = "top" | "center" | "bottom" | "sticky";
/**
 * Sets the vertical space between the content of the split layout
 */
export type VerticalGutter = "large" | "default" | "small" | "none";
/**
 * Sets the horizontal space between the content of the split layout
 */
export type HorizontalGutter = "large" | "default" | "small" | "none";
/**
 * Sets the layout of the first section
 */
export type Layout = "smallTiles" | "largeTiles" | "list";
/**
 * Sets the gutter size for the first section
 */
export type Gutter = "none" | "small" | "default" | "large";
/**
 * Whether the first section should stretch vertically to match the height of the second section
 */
export type StretchVertically = boolean;
/**
 * Sets the layout of the second section
 */
export type Layout1 = "smallTiles" | "largeTiles" | "list";
/**
 * Whether the second section should stretch vertically to match the height of the first section
 */
export type StretchVertically1 = boolean;
/**
 * Sets the gutter size for the first section
 */
export type Gutter1 = "none" | "small" | "default" | "large";
/**
 * Allowed components for the first half of the split layout
 */
export type First = (
  | BlogTeaserProps
  | BusinessCardProps
  | ButtonProps
  | ContactProps
  | ContentNavProps
  | CtaProps
  | DividerProps
  | DownloadsProps
  | EventLatestTeaserProps
  | EventListTeaserProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeadlineProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];
/**
 * Allowed components for the second half of the split layout
 */
export type Second = (
  | BlogTeaserProps
  | BusinessCardProps
  | ButtonProps
  | ContactProps
  | ContentNavProps
  | CtaProps
  | DividerProps
  | DownloadsProps
  | EventLatestTeaserProps
  | EventListTeaserProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeadlineProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];

/**
 * Split even layout component for dividing content into two equal sections.
 */
export interface SplitEvenProps {
  contentMinWidth?: ContentMinimumWidth;
  contentGutter?: ContentGutter;
  mobileReverse?: MobileReverse;
  verticalAlign?: VerticalAlignment;
  verticalGutter?: VerticalGutter;
  horizontalGutter?: HorizontalGutter;
  firstLayout?: {
    layout?: Layout;
    gutter?: Gutter;
    stretchVertically?: StretchVertically;
  };
  secondLayout?: {
    layout?: Layout1;
    stretchVertically?: StretchVertically1;
    gutter?: Gutter1;
  };
  firstComponents?: First;
  secondComponents?: Second;
}
