// Generates .design-sync/ds-entry.mjs — the single bundle entry design-sync
// needs. This package deliberately has NO barrel: rollup emits one chunk per
// `src/components/**/*Component.tsx` and package.json exposes them only via
// the `./*` subpath export, so there is nothing for `resolveDistEntry` to find.
//
// Re-run after the DS build whenever components are added/removed:
//   node .design-sync/gen-entry.mjs
//
// Why explicit named re-exports instead of `export * from`: several chunks
// export same-named helpers, and esbuild resolves ambiguous star exports to
// `undefined` silently. Explicit names make a collision a build error instead.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, "..");
const DIST = join(PKG, "dist", "components");

// Every component's SOURCE module is `<Name>Component.tsx`, and that is what
// stories import (`import { Button } from "./ButtonComponent"`). design-sync's
// import-redirect rule decides whether to point an import at the shipped
// bundle by testing the resolved FILE/DIR name against the bundle's export
// list — it sees `ButtonComponent`, the bundle exports `Button`, no match, and
// the preview quietly bundles a second copy of the component from source:
// unstyled (.scss compiles to empty) and with its own React context identity,
// so the Providers chain stops reaching it.
// Exporting a `<Name>Component` alias for every component is what makes that
// rule fire, and it costs nothing: the card roster comes from story titles, so
// aliases never become extra components.
const componentAlias = (name) => `${name}Component`;

// Form controls are the inverse case: their source export already IS
// `<Name>Component`, while the story title says "Form / Checkbox". Here the
// clean name is the alias.
const ALIASES = {
  CheckboxComponent: "Checkbox",
  CheckboxGroupComponent: "CheckboxGroup",
  RadioComponent: "Radio",
  RadioGroupComponent: "RadioGroup",
  SelectFieldComponent: "SelectField",
  TextAreaComponent: "TextArea",
  TextFieldComponent: "TextField",
};

const namedExports = (file) => {
  const names = [];
  for (const m of readFileSync(file, "utf8").matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const part of m[1].split(",")) {
      const t = part.trim();
      if (!t) continue;
      const as = t.match(/^([\w$]+)(?:\s+as\s+([\w$]+))?$/);
      if (as && as[2] !== "default") names.push(as[2] ?? as[1]);
    }
  }
  return names;
};

const pascal = (kebab) => kebab.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");

const lines = [
  "// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.",
  "// Bundle entry for design-sync: the barrel this package doesn't ship.",
  "",
  // global.css also reaches the bundle through the JS module graph
  // (page-wrapper -> global.client -> global.css). Left alone it lands AFTER
  // every component stylesheet, which inverts storybook/Vite's cascade: the
  // dev/demo rules in src/global.scss collide with real component rules at
  // identical specificity and win (e.g. hr.c-divider recolouring Divider).
  // Importing it first pins it to position 0 of the CSS graph; esbuild dedupes
  // the later import, so component CSS ends up last, exactly as in storybook.
  'import "../dist/global.css";',
  "",
];
const seen = new Map();
let count = 0;

for (const dir of readdirSync(DIST).sort()) {
  const idx = join(DIST, dir, "index.js");
  if (!existsSync(idx)) continue;
  const names = namedExports(idx);
  if (!names.length) continue; // type-only chunks (cms/, seo/) compile to nothing
  // The component whose source module is `<dir>/<Pascal(dir)>Component.tsx`.
  const primary = pascal(dir);
  const spec = [];
  for (const n of names) {
    if (seen.has(n)) {
      console.error(`  ! collision: ${n} exported by both ${seen.get(n)} and ${dir} — keeping ${seen.get(n)}`);
      continue;
    }
    seen.set(n, dir);
    const extra = [];
    if (ALIASES[n] && !seen.has(ALIASES[n])) extra.push(ALIASES[n]);
    // Source-module alias, so the import redirect resolves to the bundle.
    const srcAlias = componentAlias(n);
    if (n === primary && !seen.has(srcAlias) && !names.includes(srcAlias)) extra.push(srcAlias);
    for (const a of extra) seen.set(a, dir);
    spec.push([n, ...extra.map((a) => `${n} as ${a}`)].join(", "));
  }
  if (!spec.length) continue;
  lines.push(`export { ${spec.join(", ")} } from "../dist/components/${dir}/index.js";`);
  count += spec.length;
}

// Providers is the root wrapper every story renders inside (via PageWrapper);
// it is a default export, so the loop above skips it.
// (`providerDecorator` is already picked up by the named-export loop above —
// the source-storybook fork redirects .storybook/preview.tsx's
// `../src/components/Providers` import to the bundle, so it must be there.)
lines.push(`export { default as Providers } from "../dist/components/providers/index.js";`);
// Icon sprite: components reference <use href="#icon-..."> from this sprite.
if (existsSync(join(PKG, "dist", "tokens", "IconSprite.js"))) {
  lines.push(`export { default as IconSprite } from "../dist/tokens/IconSprite.js";`);
}
lines.push("");

writeFileSync(join(HERE, "ds-entry.mjs"), lines.join("\n"));
console.error(`ds-entry.mjs: ${count + 2} exports from ${lines.length - 5} component chunks`);
