/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the teaser card
 */
export type Headline = string;
/**
 * Body text for the teaser card
 */
export type Text = string;
/**
 * Label for the Teaser Card
 */
export type Label = string;
/**
 * Whether the Teaser Card is centered
 */
export type Centered = boolean;
/**
 * Url that should be linked
 */
export type Url = string;
/**
 * Label of the button. Still A11Y relevant when the button is hidden.
 */
export type Label1 = string;
/**
 * Toggle arrow icon
 */
export type Icon = boolean;
/**
 * Toggle wether you want the card to have a visible button or not
 */
export type DisplayButton = boolean;
/**
 * Image to display as cover
 */
export type Image = string;
/**
 * Alternative text for the image, used for accessibility
 */
export type ImageAlt = string;
/**
 * Whether the image zooms in slightly when hovering over the card
 */
export type ImageHoverEffect = boolean;

/**
 * Component used to tease content
 */
export interface TeaserCardProps {
  headline?: Headline;
  text?: Text;
  label?: Label;
  /**
   * Layout for the Teaser Card
   */
  layout?: "stack" | "row" | "compact";
  centered?: Centered;
  url: Url;
  button?: {
    label: Label1;
    chevron?: Icon;
    hidden?: DisplayButton;
  };
  image?: Image;
  imageAlt?: ImageAlt;
  /**
   * Aspect ratio of the image
   */
  imageRatio?: "wide" | "landscape" | "square" | "unset";
  imageHoverEffect?: ImageHoverEffect;
}
