/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the business card content is centered.
 */
export type Centered = boolean;
/**
 * URL of the background image shown on the business card.
 */
export type ImageSource = string;
/**
 * Alternative text describing the background image.
 */
export type ImageAltText = string;
/**
 * URL of the company or organization logo.
 */
export type LogoImage = string;
/**
 * Alternative text describing the logo.
 */
export type LogoAltText = string;
/**
 * URL to the company's website or landing page.
 */
export type LogoTarget = string;
/**
 * A headline or main topic for the business card, such as a job title or department.
 */
export type Topic = string;
/**
 * The physical or mailing address displayed on the business card.
 */
export type Address = string;
/**
 * URL of the person's avatar or profile image.
 */
export type AvatarImage = string;
/**
 * Alternative text describing the avatar.
 */
export type AvatarAltText = string;
/**
 * Label describing the contact method (e.g., 'Email', 'Phone').
 */
export type ContactLabel = string;
/**
 * Icon name or identifier representing the contact method.
 */
export type ContactIcon = string;
/**
 * URL or link for the contact method, if applicable.
 */
export type ContactURL = string;
/**
 * A list of contact methods for the person or business (e.g., email, phone, website).
 */
export type ContactInformation = {
  label: ContactLabel;
  icon?: ContactIcon;
  url?: ContactURL;
}[];
/**
 * Text label for the link.
 */
export type ButtonLabel = string;
/**
 * URL the link points to.
 */
export type ButtonURL = string;
/**
 * A list of action buttons shown on the business card.
 */
export type Buttons = {
  label: ButtonLabel;
  url: ButtonURL;
}[];

/**
 * Business card component representing an individual's or company's contact information and branding.
 */
export interface BusinessCardProps {
  centered?: Centered;
  image?: BackgroundImage;
  logo?: CompanyLogo;
  topic?: Topic;
  address?: Address;
  avatar?: Avatar;
  contactLinks?: ContactInformation;
  buttons?: Buttons;
}
/**
 * A background or feature image displayed on the business card.
 */
export interface BackgroundImage {
  src: ImageSource;
  alt?: ImageAltText;
}
/**
 * The logo of the company or organization displayed on the business card.
 */
export interface CompanyLogo {
  src: LogoImage;
  alt?: LogoAltText;
  url?: LogoTarget;
}
/**
 * A profile image or avatar representing the person on the business card.
 */
export interface Avatar {
  src: AvatarImage;
  alt?: AvatarAltText;
}
