/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Picture source
 */
export type Source1 = string;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;
/**
 * Invert the color scheme of the footer
 */
export type Inverted = boolean;
/**
 * Heading displayed above the navigation links in this column
 */
export type ColumnHeading = string;
export type Label = string;
export type URL = string;
export type OpenInNewTab = boolean;
/**
 * Navigation links in this column
 */
export type Links = {
  label: Label;
  url: URL;
  newTab?: OpenInNewTab;
}[];
/**
 * Groups of navigation links with headings, displayed as columns in the footer
 */
export type NavigationGroups = {
  heading?: ColumnHeading;
  items?: Links;
}[];
/**
 * Copyright notice displayed in the footer bottom bar
 */
export type Copyright = string;
export type Label1 = string;
export type URL1 = string;
/**
 * Icon identifier from the icon sprite (e.g. facebook, twitter, linkedin, xing)
 */
export type Icon = string;
export type URL2 = string;
/**
 * Accessible label for the social link (announced by screen readers)
 */
export type AccessibleLabel = string;
/**
 * Social media links displayed in the footer, rendered with icons from the icon sprite
 */
export type SocialLinks = {
  icon: Icon;
  url: URL2;
  ariaLabel?: AccessibleLabel;
}[];

/**
 * Footer component for displaying site logo, grouped navigation links, social links and a legal bottom bar at the bottom of the page.
 */
export interface FooterProps {
  logo: Logo;
  inverted?: Inverted;
  navGroups?: NavigationGroups;
  copyright?: Copyright;
  legalLink?: LegalLink;
  socialLinks?: SocialLinks;
}
export interface Logo {
  src?: Source;
  srcInverted?: Source1;
  alt?: AltText;
  homepageHref?: string;
  width?: Width;
  height?: Height;
}
/**
 * Link to the legal/privacy page displayed in the footer bottom bar
 */
export interface LegalLink {
  label?: Label1;
  url?: URL1;
}
