/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogTeaserProps} from "../blog-teaser/BlogTeaserProps";
import type {BusinessCardProps} from "../business-card/BusinessCardProps";
import type {ButtonProps} from "../button/ButtonProps";
import type {ContactProps} from "../contact/ContactProps";
import type {ContentNavProps} from "../content-nav/ContentNavProps";
import type {CtaProps} from "../cta/CtaProps";
import type {DividerProps} from "../divider/DividerProps";
import type {DownloadsProps} from "../downloads/DownloadsProps";
import type {EventLatestTeaserProps} from "../event-latest-teaser/EventLatestTeaserProps";
import type {EventListTeaserProps} from "../event-list-teaser/EventListTeaserProps";
import type {FaqProps} from "../faq/FaqProps";
import type {FeaturesProps} from "../features/FeaturesProps";
import type {GalleryProps} from "../gallery/GalleryProps";
import type {HeadlineProps} from "../headline/HeadlineProps";
import type {HeroProps} from "../hero/HeroProps";
import type {HtmlProps} from "../html/HtmlProps";
import type {ImageStoryProps} from "../image-story/ImageStoryProps";
import type {ImageTextProps} from "../image-text/ImageTextProps";
import type {LogosProps} from "../logos/LogosProps";
import type {MosaicProps} from "../mosaic/MosaicProps";
import type {SliderProps} from "../slider/SliderProps";
import type {StatsProps} from "../stats/StatsProps";
import type {TeaserCardProps} from "../teaser-card/TeaserCardProps";
import type {TestimonialsProps} from "../testimonials/TestimonialsProps";
import type {TextProps} from "../text/TextProps";
import type {VideoCurtainProps} from "../video-curtain/VideoCurtainProps";

/**
 * Sets the vertical space between the content of the split layout
 */
export type VerticalGutter = "large" | "default" | "small" | "none";
/**
 * Sets the horizontal space between the content of the split layout
 */
export type HorizontalGutter = "large" | "default" | "small" | "none";
/**
 * Aligns the content vertically within the sections
 */
export type VerticalAlignment = "top" | "center" | "bottom" | "sticky";
/**
 * Sets the space between the content of the split layout
 */
export type ContentGutter = "large" | "default" | "small" | "none";
/**
 * Sets the minimum width of the main section
 */
export type MinimumWidth = "narrow" | "default" | "wide";
/**
 * Whether the main section should stretch vertically to match the height of the aside section
 */
export type StretchVertically = boolean;
/**
 * Sets the layout of the main section
 */
export type Layout = "smallTiles" | "largeTiles" | "list";
/**
 * Size of gutter to use
 */
export type Gutter = "large" | "default" | "small" | "none";
/**
 * Sets the minimum width of the main section
 */
export type MinimumWidth1 = "narrow" | "default" | "wide";
/**
 * Whether the aside section should stretch vertically to match the height of the main section
 */
export type StretchVertically1 = boolean;
/**
 * Sets the layout of the main section
 */
export type Layout1 = "smallTiles" | "largeTiles" | "list";
/**
 * Determines the order of sections on mobile devices
 */
export type MobileOrder = "mainFirst" | "asideFirst";
/**
 * Determines the order of sections on desktop devices
 */
export type DesktopOrder = "mainFirst" | "asideFirst";
/**
 * Allowed components for the main half of the split layout
 */
export type Main = (
  | BlogTeaserProps
  | BusinessCardProps
  | ButtonProps
  | ContactProps
  | ContentNavProps
  | CtaProps
  | DividerProps
  | DownloadsProps
  | EventLatestTeaserProps
  | EventListTeaserProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeadlineProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];
/**
 * Allowed components for the aside half of the split layout
 */
export type Aside = (
  | BlogTeaserProps
  | BusinessCardProps
  | ButtonProps
  | ContactProps
  | ContentNavProps
  | CtaProps
  | DividerProps
  | DownloadsProps
  | EventLatestTeaserProps
  | EventListTeaserProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeadlineProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];

/**
 * Split weighted layout component for dividing content into two sections with customizable widths.
 */
export interface SplitWeightedProps {
  verticalGutter?: VerticalGutter;
  horizontalGutter?: HorizontalGutter;
  verticalAlign?: VerticalAlignment;
  mainLayout?: MainLayout;
  asideLayout?: AsideLayout;
  order?: Order;
  mainComponents?: Main;
  asideComponents?: Aside;
}
export interface MainLayout {
  gutter?: ContentGutter;
  minWidth?: MinimumWidth;
  stretchVertically?: StretchVertically;
  layout?: Layout;
}
/**
 * Layout settings for the aside section of the split layout
 */
export interface AsideLayout {
  gutter?: Gutter;
  minWidth?: MinimumWidth1;
  stretchVertically?: StretchVertically1;
  layout?: Layout1;
}
/**
 * Sets the order of the main and aside sections in the split layout
 */
export interface Order {
  mobile?: MobileOrder;
  desktop?: DesktopOrder;
}
